version: "3"
services:
    grpc_service:
        build:
            context: .
        command: npm start
        restart: always
        depends_on:
            - grpc_mongo
        environment:
            - NODE_ENV=dev
        networks:
            - grpc-net
        links:
            - grpc_mongo:mongo

    grpc_mongo:
        image: mongo:latest
        container_name: grpc_mongo
        restart: always
        volumes:
            - db-data:/data/db
        networks:
            - grpc-net
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor

    grpc_mongo-express:
        image: mongo-express
        depends_on:
            - grpc_mongo
        links:
            - grpc_mongo:mongo
        networks:
            - grpc-net
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: toor

networks:
    grpc-net:

volumes:
    db-data: