version: "3"
services:
    grpc_service:
        build:
            context: .
        command: npm start
        container_name: grpc_service
        restart: always
        depends_on:
            - grpc_mongo
        environment:
            - NODE_ENV=dev
        networks:
            - grpc-net
        links:
            - grpc_mongo:mongo
        ports: 
            - "5001:5001"
            - "5000:5000"
            - "3000:3000"

    grpc_client:
        build: 
            context: ./grpc-client
        # command: node add-vehicle-snapshot.js
        command: ping grpc_service
        container_name: grpc_client
        restart: always
        depends_on: 
            - grpc_service
        networks: 
            - grpc-net
        links: 
            - grpc_service

    grpc_mongo:
        image: mongo:latest
        container_name: grpc_mongo
        restart: always
        volumes:
            - db-data:/data/db
        networks:
            - grpc-net
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor

    grpc_mongo-express:
        image: mongo-express
        depends_on:
            - grpc_mongo
        links:
            - grpc_mongo:mongo
        networks:
            - grpc-net
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: toor

networks:
    grpc-net:

volumes:
    db-data: